# Header
menu:
  Main Page: /
  Archives: /archives
  Resume: /resume
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/fenixlin"
  weibo: "http://weibo.com/fenixl"
  #rss: /atom.xml
  zhihu: "http://www.zhihu.com/people/lin-jing-hao-17"
  #douban: "#"
  mail: mailto:fenixlin@yandex.com
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"


# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: https://avatars2.githubusercontent.com/u/4312139?v=2&s=150 
#是否开启分享
share: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "fenixlin-hexo"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
#aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
